name: Docker CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ocdarr:${{ github.sha }}-${{ matrix.platform }}
        platforms: ${{ matrix.platform }}

    - name: Tag and push "latest"
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/ocdarr:${{ github.sha }}-${{ matrix.platform }} ghcr.io/${{ github.repository_owner }}/ocdarr:latest
        docker push ghcr.io/${{ github.repository_owner }}/ocdarr:latest
