name: Docker CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            dockerfile: Dockerfile.amd64
          - arch: arm32v7
            dockerfile: Dockerfile.arm32v7
          - arch: arm64v8
            dockerfile: Dockerfile.arm64v8

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/myapp:${{ github.ref_name }}-${{ matrix.arch }}
        build-args: |
          VERSION=${{ github.ref_name }}
          ARCH=${{ matrix.arch }}

    - name: Tag "latest"
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/myapp:${{ github.ref_name }}-${{ matrix.arch }} ghcr.io/${{ github.repository_owner }}/myapp:latest
        docker push ghcr.io/${{ github.repository_owner }}/myapp:latest
